router
  .route("/")
  .get(wrapAsync(listingController.index))
  .post(
    isLoggedIn,    
    upload.single('listing[image][url]'),
    validateListing,
    wrapAsync(listingController.createListing)
  );
